sources:
  - name: "pizza_db"
    type: "sqlite"
    connection:
      filepath: "pizza.db"
    query: "SELECT name, toppings FROM pizza;"

destinations:
  - name: "delivery_db"
    type: "sqlite"
    connection:
      filepath: "delivery.db"

pipelines:
  - source: "pizza_db"
    target: "delivery_db.delivery"
    fields:
      - source: "name"
        target: "name"
      - source: "toppings"
        target: "toppings"