sources:
  - name: "pizza_db"
    type: "sqlite3"
    connection:
      filepath: "../etls/data/pizza.db"
    query: "SELECT name, toppings FROM pizza;"

targets:
  - name: "delivery_db"
    type: "sqlite3"
    connection:
      filepath: "../etls/data/delivery.db"

pipelines:
  - source: "pizza_db.pizza"
    target: "delivery_db.delivery"
    fields:
      - source: "name"
        target: "name"
      - source: "toppings"
        target: "toppings"